#!/usr/bin/env perl

# Copyright (c) 2013 Sean Malloy. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    - Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    - Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# ABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

use strict;
use warnings;
use English qw( -no_match_vars );
use Pod::Usage;
use SPM::Util qw( is_defined );
use App::Netflowd::Database qw( create_netflowd_database verify_netflowd_database );

my ($Create_Database, $Help, $Man_Page, $Verify_Database);
if (!GetOptions('create-database' => \$Create_Database,
                'help'            => \$Help,
                'manpage'         => \$Man_Page,
                'verify-database' => \$Verify_Database,)) {
    pod2usage(-exitval => 1,
              -verbose => 1, 
    );
}

if ($Help) {
    pod2usage(-exitval => 0,
              -verbose => 1,
    );
}

if ($Man_Page) {
    pod2usage(-exitval => 0,
              -verbose => 2,
    );
}

if ($Create_Database || $Verify_Database) {
    pod2usage(-exitval => 1,
              -verbose => 1, 
    );
}

my $Database_File = shift @ARGV;
is_defined($Database_File);

# create database
if ($Create_Database) {
    create_netflowd_database($Database_File);
}

# verify database
if ($Verify_Database) {
    verify_netflowd_database($Database_File);
}

exit 0;

__END__
=head1 NAME

netflowd - Netflow Collector Daemon

=head1 SYNOPSIS

  netflowd_util --create-database | --verify-database <DATABASE>
  netflowd_util --help
  netflowd_util --manpage

=head1 DESCRIPTION

Netflowd helper utility

=head1 OPTIONS

=over

=item --create-database

Create netflowd SQLite database.

=item --help

Display help and exit.

=item --manpage

Display entire manual and exit.

=item --verify-database

Verify netflowd SQLite database.

=back

=head1 EXAMPLE USAGE

    # Only create database
    netflowd_util --create-database /usr/local/etc/netflowd.db

    # Only verify database
    netflowd_util --verify-database /usr/local/etc/netflowd.db

    # Create and verify database
    netflowd_util --create-database --verify-database /usr/local/etc/netflowd.db

=head1 BUGS AND LIMITATIONS

No known bugs at this time.

=head1 SEE ALSO

App::Netflowd::Database

=head1 AUTHOR

Sean Malloy, E<lt>spinelli85@gmail.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2013 Sean Malloy. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

   - Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
   - Redistributions in binary form must reproduce the above
     copyright notice, this list of conditions and the following
     disclaimer in the documentation and/or other materials provided
     with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
ABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

=cut

